### PR TITLE
Pollend

### PR DESCRIPTION
**Pull request by javiexin**
New functionality: specify when the poll ends
(rather than just a duration in days).
Includes the use of a new event in posting (cleaner, more appropriate).
Includes rearrangement of options presented to user in posting.
Requires a change to the core, https://github.com/phpbb/phpbb/pull/3567
Covers the requirements of #37

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Sad. All commits are also in here :-/

Do you have tested the error cases, if entered illegal dates for example?
What about feb 30th?

**Comment by javiexin** [comment]
Yes, I saw them when I was creating the PR. Don't know how to do it properly. I guess if you commit the previous, you will see the actual diff.
I will do further tests, looking for those illegal dates.  I think no error is generated, but a wrong date will be selected, but will tell you.

**Comment by Wolfsblvt** [comment]
In that case you have to work on that again, sorry. There should be an error if you enter the wrong date, or it shouldn't be possible to enter the wrong date. That's the two options I can think about.

Or do you think it is okay to get wrong dates if you entered wrong stuff?

**Comment by Wolfsblvt** [comment]
Merged the other pull request, all commits still here :P

**Comment by javiexin** [comment]
Don't know why...  It seems not all are there, only the no-vote, and the poll end (I think).

**Comment by javiexin** [comment]
On the error processing: if you specify "June 31st", the poll comes out right (no error), with end date of "July 1st".  This is not ideal, but not bad either... It also happens with very wrong dates, such as "May 40th" (comes out as May 10th), or month 20 comes out as August next year.  This is the standard behaviour of the PHP mktime function (http://php.net/manual/en/function.mktime.php).
What do you prefer, to check for this error, or leave it as is?

**Comment by Wolfsblvt** [comment]
I think we should do some kind of prevention for it.
I mean if you enter a date and do a small type, like 40th may instead of 20th, you will get no notice, but the poll will last much longer than you expected. That can't be good.

I think we should either do some JS checking, or check that on server side and give a short error message, the same like when no title of a new topic is given, etc.

**Comment by javiexin** [comment]
Ok, will code that and include it.

**Comment by Wolfsblvt** [comment]
Thank you (:
I think our Extension will be awesome!

**Comment by javiexin** [comment]
Arggg...  This error processing is killing me.  Detecting the error is one line of PHP code.  But the problem is how to act on it, according to the same way that is done with other errors when posting (such as "no poll title" or "too many poll options").  These are detected in an specific function, $message_parser->parse_poll, that has no events.  And in the other places where I am trying to intercept this, either there is not enough context, or it is not possible to return the error the right way.  In summary, that doing such a stupid simple thing is taking far too much time!  Anyhow, I will get it done... but we will need to use a separate core event just for this (for sure), and possibly complicate more the code, and delay (slightly) the execution.

**Comment by Wolfsblvt** [comment]
What happens when you just throw an exception?
That should be the way to give errors in the new phpBB. I think you just have to check if the things entered are correct, otherwise throw one of the new exceptions.

**Comment by javiexin** [comment]
New commit with date validation.
Requires the use of another event, and some code duplication because of lack of correct data at every event location. Will open issue in bugtracker, but works as is here.

**Comment by javiexin** [comment]
If end date/time is not configured in ACP, or is not specified in the poll, length is used instead, as in normal polls.  Tested.  No check required here.  By the way, chat?.

**Pull request merged**
