### PR TITLE
Moderator view poll results

### LINKED ISSUE #31: Ability for admins/mods to see all voters (permission based)
Add an admin/mod level permission to see all voters of a poll, regardless of specific poll settings.

### PR DESCRIPTION
**Pull request by javiexin**
Adds a (by forum) permission for moderators to see all voters of the polls, regardless of the poll visibility settings.  Only mods with the right permission can ask for this, and it is only provided on demand.
There are a couple of hacks on the HTML, due to the lack of appropriate template events (HTML div inside a h3 block, and HTML code extending a label text from code).
Will ask for additional events, and if approved, this can be improved.
    
Closes #31

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
What's that first commit?
Isn't that the stuff you have already done in the last PR, or am I just confused?

**Comment by javiexin** [comment]
Yes, i think it is the last commit, that was duplicated when I merged it back to my master branch

**Comment by Wolfsblvt** [comment]
Then you have probably done something wrong. The commit should not be added to this PR again.
Let's hope merging is working now.

**Comment by javiexin** [comment]
Hope so, because the code has not changed.

**Pull request merged**
