### PR TITLE
Update info_acp_advancedpolls.php

### PR DESCRIPTION
**Pull request by Maskinisten**

### CODE REVIEW

**Comment by javiexin** [comment]
There are a lot of new strings, and a few updated.  Please, complete all translation of the new version.

**Comment by Maskinisten** [comment]
I compared the German version with my existing translation. Is the German version not up to date?

**Comment by javiexin** [comment]
No, the German version is not updated.  The reliable version is English.
Other existing and complete translations are Spanish, Italian, Russian and Dutch.

**Comment by Galixte** [comment]
…and french. ;)

**Comment by javiexin** [comment]
Indeed... I forgot here, but not in the phpbb forum

**Pull request closed without merging**
